//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPTravel.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPTravel.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OpenAI API Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sk-... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("ApiKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I am driving on a road trip. The departure point is Los Angeles, and the destination is New York. The departure date and time are [Year] [Month] [Day] [Hour]:[Minute]. Based on the following location information and time, please briefly describe my travel progress and tell me about the culture and history of the area I am currently in. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BasePrompt_Default {
            get {
                return ResourceManager.GetString("BasePrompt_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Example に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExampleSentence {
            get {
                return ResourceManager.GetString("ExampleSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location information and the current date and time will be attached to this text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Info_LocationAndTimeNotice {
            get {
                return ResourceManager.GetString("Info_LocationAndTimeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speech interval (min) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IntervalPickerTitle {
            get {
                return ResourceManager.GetString("IntervalPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguagePickerTitle {
            get {
                return ResourceManager.GetString("LanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelPickerTitle {
            get {
                return ResourceManager.GetString("ModelPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If your OpenAI API key is incorrect or your API usage has not been billed, the message “Payment required” will appear. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PaymentRequiredNotice {
            get {
                return ResourceManager.GetString("PaymentRequiredNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base Prompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start GPTravel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPTravel Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
